### ISSUE TITLE
why is the hold option dont have a cps adjustment?

### ISSUE THREAD

**Issue by KRIZZGETHUB** [WorldOfBasti/MaClicker#1]
Hi sir, can you please release an update so I can adjust my CPS on the hold option? I am trying to support this application so I can make a YouTube video about it. I really like it, but I just need your help. Hopefully you understand.

**Comment by WorldOfBasti** [comment]
Hello,
thanks for your support.

What exactly do you mean by adjust the cps with the hold option?
I have designed the hold-option like this: It holds the mouse button permanently until you press the hotkey.

Please describe it in more detail so I can help you.

**Comment by KRIZZGETHUB** [comment]
I appreciate your response. I was wondering why it is possible to adjust the CPS on the click option but not on the hold part. I really need to change it because it is only pulling around 15 CPS, Oh, and could you please add a left click hold option? I personally use your auto clicker for a Roblox game that I really enjoy playing,  hopefully you understand.

**Comment by WorldOfBasti** [comment]
CPS = Clicks per second or click speed. If you select the "Hold" option, the mouse button is only held. So clicks make no sense...
I attached an example video showing first the Hold-option and then the Click-option (where you can select the click speed (clicks per second or CPS).

So CPS with the Hold-option makes no sense to me? What do you expect to happen there?

https://github.com/user-attachments/assets/df6ce39e-bf1c-40ab-bcd3-8492f9b3055d

**Comment by KRIZZGETHUB** [comment]
Thank you for your reply. I understand, but I'm not sure if it's possible to do things like unlock the CPS on the Hold option or just create a left click hold where you hold down the left click and it automatically clicks. I really want it that way, but I'm not sure if it's possible because there's this auto clicker that I really want to get, but it's only available on Windows OS, and unfortunately, I don't have a Windows device, so I'm not sure if you can make it work the way I want it. Could you please make it like this type of auto clicker that my Windows friends uses? https://fabi.me/en/tools/speed-autoclicker/ You can copy and paste it into your browser if you'd like, but if you're not comfortable doing so, then that's okay . I'm just asking for one small thing, so hopefully you understand.

**Comment by WorldOfBasti** [comment]
Ahhhh ok, I think I've got it now. 
So you want to expect that if you select Hold-option, the clicker only clicks when you hold the key, right?
I think I can have a look at this by next week.

**Comment by KRIZZGETHUB** [comment]
Thank u for understanding sir 😁

**Comment by KRIZZGETHUB** [comment]
Hello sir, just a friendly reminder to keep working on the auto clicker code I explained. As the week is almost over and there hasn't been a new update release, I'm starting to get down because I need a good auto clicker to help me with a game that requires auto clicking. Please let me know if you're almost finished coding, sir, so it can brighten my day.

**Comment by WorldOfBasti** [comment]
Thanks for your strong interest in that update.
I had a few other things to do, so it has been a bit delayed.
I guess I can roll out the release tomorrow. I'll report back here then.

**Comment by KRIZZGETHUB** [comment]
Thank you very much for your reply, sir. I'm thrilled that the update is ready today. I hope you worked hard on the auto clicker and that it includes the additional features I described. If so, I'll be posting it to YouTube explaining it.

**Comment by KRIZZGETHUB** [comment]
God bless you, thank you, world of basti. I am so grateful for this. You made my day.

**Comment by KRIZZGETHUB** [comment]
Greetings, worldofbasti  I appreciate the improvement you made, however I find the activation key bind to be annoying because I would prefer to hold it on my mouse left click button rather than on my keyboard. Please, I'm not sure whether you can finish it for me pls.
